//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.ServiceNearestStore {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNearestStore.IServiceNearestStore")]
    public interface IServiceNearestStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNearestStore/GetNearestStore", ReplyAction="http://tempuri.org/IServiceNearestStore/GetNearestStoreResponse")]
        string GetNearestStore(string storeName, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNearestStore/GetNearestStore", ReplyAction="http://tempuri.org/IServiceNearestStore/GetNearestStoreResponse")]
        System.Threading.Tasks.Task<string> GetNearestStoreAsync(string storeName, string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNearestStoreChannel : account.ServiceNearestStore.IServiceNearestStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNearestStoreClient : System.ServiceModel.ClientBase<account.ServiceNearestStore.IServiceNearestStore>, account.ServiceNearestStore.IServiceNearestStore {
        
        public ServiceNearestStoreClient() {
        }
        
        public ServiceNearestStoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNearestStoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNearestStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNearestStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetNearestStore(string storeName, string location) {
            return base.Channel.GetNearestStore(storeName, location);
        }
        
        public System.Threading.Tasks.Task<string> GetNearestStoreAsync(string storeName, string location) {
            return base.Channel.GetNearestStoreAsync(storeName, location);
        }
    }
}
