//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.NationalWeather {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalWeather.INationalWeatherService")]
    public interface INationalWeatherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalWeatherService/GetWeatherForecast", ReplyAction="http://tempuri.org/INationalWeatherService/GetWeatherForecastResponse")]
        string[] GetWeatherForecast(string zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalWeatherService/GetWeatherForecast", ReplyAction="http://tempuri.org/INationalWeatherService/GetWeatherForecastResponse")]
        System.Threading.Tasks.Task<string[]> GetWeatherForecastAsync(string zipcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalWeatherServiceChannel : account.NationalWeather.INationalWeatherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalWeatherServiceClient : System.ServiceModel.ClientBase<account.NationalWeather.INationalWeatherService>, account.NationalWeather.INationalWeatherService {
        
        public NationalWeatherServiceClient() {
        }
        
        public NationalWeatherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalWeatherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalWeatherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalWeatherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetWeatherForecast(string zipcode) {
            return base.Channel.GetWeatherForecast(zipcode);
        }
        
        public System.Threading.Tasks.Task<string[]> GetWeatherForecastAsync(string zipcode) {
            return base.Channel.GetWeatherForecastAsync(zipcode);
        }
    }
}
