//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.ServiceNumber2Words {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceNumber2Words.IServiceNumber2Words")]
    public interface IServiceNumber2Words {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNumber2Words/Number2Words", ReplyAction="http://tempuri.org/IServiceNumber2Words/Number2WordsResponse")]
        string Number2Words(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNumber2Words/Number2Words", ReplyAction="http://tempuri.org/IServiceNumber2Words/Number2WordsResponse")]
        System.Threading.Tasks.Task<string> Number2WordsAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNumber2WordsChannel : account.ServiceNumber2Words.IServiceNumber2Words, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNumber2WordsClient : System.ServiceModel.ClientBase<account.ServiceNumber2Words.IServiceNumber2Words>, account.ServiceNumber2Words.IServiceNumber2Words {
        
        public ServiceNumber2WordsClient() {
        }
        
        public ServiceNumber2WordsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNumber2WordsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNumber2WordsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNumber2WordsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Number2Words(string number) {
            return base.Channel.Number2Words(number);
        }
        
        public System.Threading.Tasks.Task<string> Number2WordsAsync(string number) {
            return base.Channel.Number2WordsAsync(number);
        }
    }
}
