//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.POIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="POIService.IPOIService")]
    public interface IPOIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOIService/PoiSearch", ReplyAction="http://tempuri.org/IPOIService/PoiSearchResponse")]
        string[] PoiSearch(string location, string keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOIService/PoiSearch", ReplyAction="http://tempuri.org/IPOIService/PoiSearchResponse")]
        System.Threading.Tasks.Task<string[]> PoiSearchAsync(string location, string keywords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOIService/FindLocation", ReplyAction="http://tempuri.org/IPOIService/FindLocationResponse")]
        string FindLocation(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPOIService/FindLocation", ReplyAction="http://tempuri.org/IPOIService/FindLocationResponse")]
        System.Threading.Tasks.Task<string> FindLocationAsync(string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPOIServiceChannel : account.POIService.IPOIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class POIServiceClient : System.ServiceModel.ClientBase<account.POIService.IPOIService>, account.POIService.IPOIService {
        
        public POIServiceClient() {
        }
        
        public POIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public POIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] PoiSearch(string location, string keywords) {
            return base.Channel.PoiSearch(location, keywords);
        }
        
        public System.Threading.Tasks.Task<string[]> PoiSearchAsync(string location, string keywords) {
            return base.Channel.PoiSearchAsync(location, keywords);
        }
        
        public string FindLocation(string location) {
            return base.Channel.FindLocation(location);
        }
        
        public System.Threading.Tasks.Task<string> FindLocationAsync(string location) {
            return base.Channel.FindLocationAsync(location);
        }
    }
}
