//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.ServiceStemming {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStemming.IServiceStemming")]
    public interface IServiceStemming {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStemming/GetStem", ReplyAction="http://tempuri.org/IServiceStemming/GetStemResponse")]
        string GetStem(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStemming/GetStem", ReplyAction="http://tempuri.org/IServiceStemming/GetStemResponse")]
        System.Threading.Tasks.Task<string> GetStemAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStemmingChannel : account.ServiceStemming.IServiceStemming, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStemmingClient : System.ServiceModel.ClientBase<account.ServiceStemming.IServiceStemming>, account.ServiceStemming.IServiceStemming {
        
        public ServiceStemmingClient() {
        }
        
        public ServiceStemmingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStemmingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStemmingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStemmingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStem(string value) {
            return base.Channel.GetStem(value);
        }
        
        public System.Threading.Tasks.Task<string> GetStemAsync(string value) {
            return base.Channel.GetStemAsync(value);
        }
    }
}
